version: '3'

services:
  social:
    container_name: social
    build:
      context: '..'
      dockerfile: ./docker/Dockerfile
    expose:
      - 3000
    environment:
      NODE_ENV: production

  nginx:
    build: ./nginx
    ports:
      - "3005:80"
    depends_on:
      - social

